name: Yeast genealogy preview

# Branch genealogy-preview must exist for this action to work.

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build_plots_and_publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.YEAST }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Wait for other instances to complete
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
      
      - name: Generate Image, Commit and Push Image
        run: |
          git config user.name "Evgenii-Barannik"
          git config user.email "radchemsu@gmail.com"
          git config --global credential.helper store
          
          echo "https://${PERSONAL_ACCESS_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials

          git fetch

          cargo run --verbose
          cat genealogy.dot | dot -Tpng > genealogy.png

          cp genealogy.png ../genealogy.png
          git restore .
          git switch genealogy-preview
          cp ../genealogy.png genealogy-${COMMIT_SHA}.png
          git add genealogy-${COMMIT_SHA}.png
          git commit --allow-empty -m "Yeast genealogy preview action"
          git push origin HEAD:genealogy-preview

      - name: Publish Image
        run: |
          IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/genealogy-preview/genealogy-${COMMIT_SHA}.png"
          COMMENT="![Generated Image]($IMAGE_URL)"
          COMMENT_URL=$(jq -r .pull_request.comments_url "$GITHUB_EVENT_PATH")
          curl -H "Authorization: token $PERSONAL_ACCESS_TOKEN" -H "Content-Type: application/json" -X POST --data "{\"body\": \"$COMMENT\"}" "$COMMENT_URL"
