name: Yeast genealogy preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Checkout, Generate Image, Commit and Push Image
        env:
          MY_GITHUB_TOKEN: ${{ secrets.YEAST }}
        run: |
          git config user.name "Evgenii-Barannik"
          git config user.email "radchemsu@gmail.com"
          git fetch
          cargo run --verbose
          cat genealogy.dot | dot -Tpng > genealogy.png
          git add genealogy.png
          git restore .
          git commit --allow-empty -m "Yeast genealogy preview action"
          git push https://${MY_GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:genealogy-preview

      - name: Publish Image
        env:
          MY_GITHUB_TOKEN: ${{ secrets.YEAST }}
        run: |
          IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/genealogy-preview/genealogy.png"
          COMMENT="![Generated Image]($IMAGE_URL)"
          COMMENT_URL=$(jq -r .pull_request.comments_url "$GITHUB_EVENT_PATH")
          curl -H "Authorization: token $MY_GITHUB_TOKEN" -H "Content-Type: application/json" -X POST --data "{\"body\": \"$COMMENT\"}" "$COMMENT_URL"
